logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mugglelee.top:12345/cloud_file?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/cloud_file?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: mugglelee.top
    port: 8084
    username: guest
    password: 123456
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://mugglelee.top:8092
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1
mybatis:
  type-aliases-package: com.hao.filecenter.Model
  mapper-locations: classpath:/mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
#      user-info-uri: http://mugglelee.top:8093/api-o/user-me
      user-info-uri: http://127.0.0.1:8093/api-o/user-me
      prefer-token-info: false
file:
  local:
    path: Document/Github/Download
    prefix: /statics
#    urlPrefix: http://47.107.104.181:8093/api-f${file.local.prefix}
    urlPrefix: http://127.0.0.1:8093/api-f${file.local.prefix}
#  aliyun:
#    endpoint: xxx
#    accessKeyId: xxx
#    accessKeySecret: xxx
#    bucketName: xxx
#    domain: https://xxx