logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.104.181:12345/cloud_user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
#  rabbitmq:
#    host: local.rabbitmq.com
#    port: 5672
#    username: cloud-dev
#    password: cloud-dev
#    virtual-host: /
  redis:
    host: 47.107.104.181
    port: 8083
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#    sender:
#      type: web
mybatis:
  type-aliases-package: com.hao.commonmodel.Model.User
  mapper-locations: classpath:/Mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
#      user-info-uri: http://local.gateway.com:8080/api-o/user-me
#      user-info-uri: http://127.0.0.1:8082/user-me
      user-info-uri: http://127.0.0.1:8093/api-o/user-me
      prefer-token-info: false
#wechat:
#  domain: http://api.gateway.com:8080/api-u
#  infos:
#    app1:
#      appid: xxx
#      secret: xxx
#    app2:
#      appid: xxx
#      secret: xxx
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000